### ISSUE TITLE
Issue running lint on windows

### ISSUE THREAD

**Issue by agruszynski** [preboot/angular2-webpack#109]
I cloned the latest on 2 windows machines and my mac.  Node and npm are at the latest versions on all three machines.  After executing npm install, I try to run 'npm run lint' and both windows machines fail.  Error : 
C:\dev\preboot\node_modules\tslint\node_modules\glob\sync.js:29
    throw new Error('must provide pattern')
    ^

Error: must provide pattern
    at new GlobSync (C:\dev\preboot\node_modules\tslint\node_modules\glob\sync.js:29:11)
    at Function.globSync [as sync] (C:\dev\preboot\node_modules\tslint\node_modules\glob\sync.js:24:10)
    at Object.<anonymous> (C:\dev\preboot\node_modules\tslint\lib\tslint-cli.js:128:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\dev\preboot\node_modules\tslint\bin\tslint:3:1)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Programs\\nodejs\\node.exe" "C:\\Users\\Adam\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v4.4.5
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! app@0.0.0 lint: `tslint 'src/**/*.ts'; exit 0`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app@0.0.0 lint script 'tslint 'src/**/*.ts'; exit 0'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tslint 'src/**/*.ts'; exit 0
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\preboot\npm-debug.log

Any suggestions?

**Comment by Foxandxss** [comment]
Yes sorry, I have a fix on a PR, will merge later.
