### ISSUE TITLE
Error on npm run start

### ISSUE THREAD

**Issue by Ibrahim-Islam** [preboot/angular2-webpack#160]
I mapped my existing app to this project and now when running `npm run start` I get the following error:
```
 70% 3/3 build modulesevents.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at net.js:1376:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
```

Any ideas as to what might cause this error is highly appreciated

**Comment by phra** [comment]
as the error states `Error: listen EADDRINUSE 127.0.0.1:8080`
you have a running process that is using that port.
to find the PID on linux:
`$ netstat -tulpn`

to kill the process:
`$ kill -15 <PID>`
or
`$ killall <NAME>`

for more information:
`$ man netstat`
`$ man kill`
`$ man killall`
