### ISSUE TITLE
ERROR on npm start on Windows

### ISSUE THREAD

**Issue by adrien59cadri** [preboot/angular2-webpack#205]
Hello I tried a very simple setup by cloning the repo,
ran `npm install` and `npm start`

The server actually starts and the website works on localhost:8080,
BUT I have this error in my bash even before the server starts,

do you have any idea of what i could do to solve it,

For the same reason, the e2e test fails all the time.

Best

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\adrien courdavault>cd breakfast

C:\Users\adrien courdavault\breakfast>npm start

> app@0.0.0 start C:\Users\adrien courdavault\breakfast
> npm run server


> app@0.0.0 server C:\Users\adrien courdavault\breakfast
> webpack-dashboard -- webpack-dev-server --inline --port 8080

Error: listen EADDRINUSE :::9838
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at Server.listen.Server.attach (C:\Users\adrien courdavault\breakfast\node_modules\webpack-dashboard\node_modules\socket.io\lib\index.js:216:9)
    at new Server (C:\Users\adrien courdavault\breakfast\node_modules\webpack-dashboard\node_modules\socket.io\lib\index.js:50:17)
    at Server (C:\Users\adrien courdavault\breakfast\node_modules\webpack-dashboard\node_modules\socket.io\lib\index.js:38:41)
    at Object.<anonymous> (C:\Users\adrien courdavault\breakfast\node_modules\webpack-dashboard\bin\webpack-dashboard.js:42:14)
    at Module._compile (module.js:556:32)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "server"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! app@0.0.0 server: `webpack-dashboard -- webpack-dev-server --inline --port 8080`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app@0.0.0 server script 'webpack-dashboard -- webpack-dev-server --inline --port 8080'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dashboard -- webpack-dev-server --inline --port 8080
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\adrien courdavault\breakfast\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! app@0.0.0 start: `npm run server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app@0.0.0 start script 'npm run server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\adrien courdavault\breakfast\npm-debug.log

C:\Users\adrien courdavault\breakfast>
```

**Comment by Foxandxss** [comment]
Do you have `npm start` running when you execute `npm run e2e` ?
