### ISSUE TITLE
npm run clean failed

### ISSUE THREAD

**Issue by BrkCoder** [preboot/angular2-webpack#304]
I am runing npm install in the beginning, then I run npm run build then npm run clean and I get the following errors, I attached the errors from the npm-debug file:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'clean' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 verbose run-script [ 'preclean', 'clean', 'postclean' ]
5 info lifecycle app@0.0.0~preclean: app@0.0.0
6 silly lifecycle app@0.0.0~preclean: no script for preclean, continuing
7 info lifecycle app@0.0.0~clean: app@0.0.0
8 verbose lifecycle app@0.0.0~clean: unsafe-perm in lifecycle true
9 verbose lifecycle app@0.0.0~clean: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\barak\WebstormProjects\my-app\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Users\barak\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\barak\AppData\Roaming\npm;C:\Python27\;C:\Python27\Scripts\;C:\adb;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\Python27\;C:\Python27\Scripts\;C:\Users\barak\AppData\Local\Microsoft\WindowsApps;;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\barak\AppData\Roaming\npm
10 verbose lifecycle app@0.0.0~clean: CWD: C:\Users\barak\WebstormProjects\my-app
11 silly lifecycle app@0.0.0~clean: Args: [ '/d /s /c',
11 silly lifecycle   'rimraf node_modules doc dist && npm cache clean' ]
12 silly lifecycle app@0.0.0~clean: Returned: code: 1  signal: null
13 info lifecycle app@0.0.0~clean: Failed to exec clean script
14 verbose stack Error: app@0.0.0 clean: `rimraf node_modules doc dist && npm cache clean`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid app@0.0.0
16 verbose cwd C:\Users\barak\WebstormProjects\my-app
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "clean"
19 error node v7.5.0
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error app@0.0.0 clean: `rimraf node_modules doc dist && npm cache clean`
22 error Exit status 1
23 error Failed at the app@0.0.0 clean script 'rimraf node_modules doc dist && npm cache clean'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the app package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     rimraf node_modules doc dist && npm cache clean
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs app
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls app
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mcescalante** [comment]
I was able to run `npm run clean` on a fresh clone just now, but am on macOS, so this could be a Windows issue. This error output isn't terribly helpful either; can you run `npm cache clean` alone without producing errors?

**Comment by Foxandxss** [comment]
I get an error in windows as well. Investigating...

**Comment by BrkCoder** [comment]
thanks npm cache clean solved , isse can be closed.

**Comment by BrkCoder** [comment]
I close this issue.
