### ISSUE TITLE
npm run e2e-live failed

### ISSUE THREAD

**Issue by BrkCoder** [preboot/angular2-webpack#305]
Hey I am trying to run the following command: npm run e2e-live and it failed to load the page.
I have tried it on clean project of angular2-webpack and got the following errors:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'e2e-live' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 verbose run-script [ 'pree2e-live', 'e2e-live', 'poste2e-live' ]
5 info lifecycle app@0.0.0~pree2e-live: app@0.0.0
6 silly lifecycle app@0.0.0~pree2e-live: no script for pree2e-live, continuing
7 info lifecycle app@0.0.0~e2e-live: app@0.0.0
8 verbose lifecycle app@0.0.0~e2e-live: unsafe-perm in lifecycle true
9 verbose lifecycle app@0.0.0~e2e-live: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\barak\WebstormProjects\my-app\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Users\barak\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\barak\AppData\Roaming\npm;C:\Python27\;C:\Python27\Scripts\;C:\adb;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\Python27\;C:\Python27\Scripts\;C:\Users\barak\AppData\Local\Microsoft\WindowsApps;;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\barak\AppData\Roaming\npm
10 verbose lifecycle app@0.0.0~e2e-live: CWD: C:\Users\barak\WebstormProjects\my-app
11 silly lifecycle app@0.0.0~e2e-live: Args: [ '/d /s /c', 'protractor --elementExplorer' ]
12 silly lifecycle app@0.0.0~e2e-live: Returned: code: 1  signal: null
13 info lifecycle app@0.0.0~e2e-live: Failed to exec e2e-live script
14 verbose stack Error: app@0.0.0 e2e-live: `protractor --elementExplorer`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid app@0.0.0
16 verbose cwd C:\Users\barak\WebstormProjects\my-app
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "e2e-live"
19 error node v7.5.0
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error app@0.0.0 e2e-live: `protractor --elementExplorer`
22 error Exit status 1
23 error Failed at the app@0.0.0 e2e-live script 'protractor --elementExplorer'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the app package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     protractor --elementExplorer
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs app
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls app
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mcescalante** [comment]
Have you actually run `npm install` after cloning? Again, this error output isn't very telling, and it seems like it's an error with your OS/environment, since you're getting the same error for `npm run clean`

**Comment by BrkCoder** [comment]
You are right,Can I print screen my console and then post it on here and then we will have a clue what it is?

**Comment by BrkCoder** [comment]
I close this issue.
