### ISSUE TITLE
karma says I am missing plugins

### ISSUE THREAD

**Issue by GaryB432** [preboot/angular2-webpack#83]
on my Windows 10 machine I get this from `karma start`

```
C:\Users\Me\Documents\GitHub\angular2-webpack>karma start
05 05 2016 10:53:13.622:WARN [preprocess]: Can not load "webpack", it is not registered!
  Perhaps you are missing some plugin?
05 05 2016 10:53:13.622:WARN [preprocess]: Can not load "sourcemap", it is not registered!
  Perhaps you are missing some plugin?
05 05 2016 10:53:13.653:WARN [reporter]: Can not load "coverage", it is not registered!
  Perhaps you are missing some plugin?
C:\Users\Me\AppData\Roaming\npm\node_modules\karma\node_modules\di\lib\injector.js:9
      throw error('No provider for "' + name + '"!');
      ^

Error: No provider for "framework:jasmine"! (Resolving: framework:jasmine)
    at error (C:\Users\Me\AppData\Roaming\npm\node_modules\karma\node_modules\di\lib\injector.js:22:12)
    at Object.parent.get (C:\Users\Me\AppData\Roaming\npm\node_modules\karma\node_modules\di\lib\injector.js:9:13)
    at get (C:\Users\Me\AppData\Roaming\npm\node_modules\karma\node_modules\di\lib\injector.js:54:19)
    at C:\Users\Me\AppData\Roaming\npm\node_modules\karma\lib\server.js:138:20
    at Array.forEach (native)
    at Server._start (C:\Users\Me\AppData\Roaming\npm\node_modules\karma\lib\server.js:137:21)
    at invoke (C:\Users\Me\AppData\Roaming\npm\node_modules\karma\node_modules\di\lib\injector.js:75:15)
    at Server.start (C:\Users\Me\AppData\Roaming\npm\node_modules\karma\lib\server.js:102:18)
    at Object.exports.run (C:\Users\Me\AppData\Roaming\npm\node_modules\karma\lib\cli.js:243:26)
    at Object.<anonymous> (C:\Users\Me\AppData\Roaming\npm\node_modules\karma\bin\karma:3:23)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by Foxandxss** [comment]
You have to use `npm test` because that will set some webpack configuration. Once we can update to webpack 2, that need will be removed.

**Comment by GaryB432** [comment]
Beautiful!  Thanks!  100% coverage too!

**Comment by Foxandxss** [comment]
Coverage is wrong.

It was never 100% because we were running it against transpiled code and now it gives 100% for no good reason. Will check.

**Comment by Foxandxss** [comment]
Actually no, it is good.

**Comment by jorawarsingh** [comment]
Tried npm test but same result.
 karma start
18 10 2016 17:48:12.560:ERROR [preprocess]: Can not load "webpack", it is not registered!
  Perhaps you are missing some plugin?
18 10 2016 17:48:12.560:ERROR [preprocess]: Can not load "sourcemap", it is not registered!
  Perhaps you are missing some plugin?

C:\Users\js.BLINFO\AppData\Roaming\npm\node_modules\karma\node_modules\di\lib\injector.js:22
    return new Error(stack ? msg + ' (Resolving: ' + stack + ')' : msg);
           ^
Error: No provider for "framework:jasmine"! (Resolving: framework:jasmine)
    at error (C:\Users\js.BLINFO\AppData\Roaming\npm\node_modules\karma\node_modules\di\lib\injector.js:22:12)
    at Object.get (C:\Users\js.BLINFO\AppData\Roaming\npm\node_modules\karma\node_modules\di\lib\injector.js:9:13)
    at Injector.get (C:\Users\js.BLINFO\AppData\Roaming\npm\node_modules\karma\node_modules\di\lib\injector.js:54:19)
    at C:\Users\js.BLINFO\AppData\Roaming\npm\node_modules\karma\lib\server.js:143:20
    at Array.forEach (native)
    at Server._start (C:\Users\js.BLINFO\AppData\Roaming\npm\node_modules\karma\lib\server.js:142:21)
    at Injector.invoke (C:\Users\js.BLINFO\AppData\Roaming\npm\node_modules\karma\node_modules\di\lib\injector.js:75:15)
    at Server.start (C:\Users\js.BLINFO\AppData\Roaming\npm\node_modules\karma\lib\server.js:103:18)
    at Object.exports.run (C:\Users\js.BLINFO\AppData\Roaming\npm\node_modules\karma\lib\cli.js:280:26)
    at Object.<anonymous> (C:\Users\js.BLINFO\AppData\Roaming\npm\node_modules\karma\bin\karma:3:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
npm ERR! Test failed.  See above for more details.
